# Generated by Django 3.2 on 2021-04-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='title',
            new_name='full_name',
        ),
    ]
