# Generated by Django 3.2 on 2021-04-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamSite', '0003_players_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(max_length=150, verbose_name='Название турнира')),
                ('t_content', models.TextField(blank=True, verbose_name='О туринире')),
                ('place', models.CharField(blank=True, max_length=150, verbose_name='Место')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано(Дата)')),
                ('photo', models.ImageField(blank=True, upload_to='upload/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['-created_at'], 'verbose_name': 'Игрока', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterField(
            model_name='players',
            name='content',
            field=models.TextField(blank=True, verbose_name='Об игроке'),
        ),
        migrations.AlterField(
            model_name='players',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Имя Фамилия'),
        ),
    ]
