# Generated by Django 3.2 on 2021-04-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamSite', '0004_auto_20210427_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
